server:
  port: 8087
spring:
  profiles:
    include: jdbc
  preread:
    #文件上传目录（注意Linux和Windows上的目录结构不同）
    uploadPath: E:/image/

# MyBatis 映射配置
mybatis:
  typeAliasesPackage: com.ecologicalRanch.project
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

#MQTT连接设置
mqtt:
  HOST: tcp://10.12.11.32:1883
  userName: zengyong
  passWord: zengyong312
  TOPIC1 : qwe
  clientId : selver

calculation:
  Calibration: 60
  #环境因数
  EnvironmentalFactor: 3.8
  #rssi允许偏差
  Deviation: 5
  #步数误差
  Error: 10
  #预测误差的方差
  Varianc: 8.2
  #噪声误差的方差
  NoiseVariance: 100






